on:
  push:
    branches: [ main ]
  pull_request:
permissions:
  contents: read
  pull-requests: write
name: ADO.NET Tests
jobs:
  units:
    strategy:
      matrix:
        dotnet-version: ['8.0.x', '9.0.x']
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Install dotnet
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: spanner-ado-net-tests
        working-directory: spanner-ado-net/spanner-ado-net-tests
        run: dotnet test --verbosity normal
        shell: bash
      - name: spanner-ado-net-specification-tests
        working-directory: spanner-ado-net/spanner-ado-net-specification-tests
        run: dotnet test --verbosity normal
        shell: bash
      - name: spanner-ado-net-sample-tests
        working-directory: spanner-ado-net/spanner-ado-net-samples-tests
        run: dotnet test --verbosity normal
        shell: bash
