on:
  push:
    branches: [ main ]
  pull_request:
permissions:
  contents: read
  pull-requests: write
name: ADO.NET Tests
jobs:
  units:
    strategy:
      matrix:
        dotnet-version: ['8.0.x', '9.0.x']
        os: [ubuntu-latest, macos-latest, windows-latest, ubuntu-24.04-arm]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Install dotnet
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.26.x'
      - name: Checkout go-sql-spanner
        uses: actions/checkout@v6
        with:
          repository: 'googleapis/go-sql-spanner'
          path: spanner-ado-net/spanner-ado-net/go-sql-spanner
      - name: Build SpannerLib binaries
        run: ./build-binaries.sh true
        working-directory: spanner-ado-net/spanner-ado-net
        shell: bash
      - name: spanner-ado-net-tests
        working-directory: spanner-ado-net/spanner-ado-net-tests
        run: dotnet test --verbosity normal
        shell: bash
      - name: spanner-ado-net-specification-tests
        working-directory: spanner-ado-net/spanner-ado-net-specification-tests
        run: dotnet test --verbosity normal
        shell: bash
      - name: spanner-ado-net-sample-tests
        working-directory: spanner-ado-net/spanner-ado-net-samples-tests
        run: dotnet test --verbosity normal
        shell: bash
        if: matrix.os != 'ubuntu-24.04-arm'
      - name: dotnet run sample
        working-directory: spanner-ado-net/spanner-ado-net-samples
        run: dotnet run HelloWorld
        shell: bash
        # Docker is only supported on Linux on GitHub Actions
        if: runner.os == 'Linux' && matrix.os != 'ubuntu-24.04-arm'
